from conftest import trikolad

def test_e2e(trikolad):
        trikolad.open()
        trikolad.select_product_category("Шоколад кондитерський")
        trikolad.select_position_by_link("Чорний")
        trikolad.add_to_cart(2)
        trikolad.press_continue_buying_button()
        trikolad.pause(1000)
        trikolad.select_product_category("Упакування, сервірування")
        trikolad.select_position_by_link("Коробки")
        trikolad.select_position_by_heading("Коробки для цукерок та плиток")
        trikolad.add_to_cart(2)
        trikolad.select_position_by_row("Новорічна. Коробка для 9")
        trikolad.fill_position_by_row("Шоколад чорний 55% (C501/J),",5)
        trikolad.press_continue_buying_button()
        trikolad.select_product_category("Інгредієнти кондитерські")
        trikolad.select_position_by_heading("Начинки та пасти")
        trikolad.select_position_by_heading("Паста фісташкова")
        trikolad.add_to_cart(2)
        trikolad.remove_from_cart("Фісташкова паста натуральна")
        trikolad.pause(5000)
        #trikolad.make_order()
        #trikolad.check_order()
        trikolad.close()